version: '3.5'
services:
  web:
    platform: "linux/amd64"
    build: .
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://database:3306/vetcare?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: VetCare_DB
      spring.datasource.password: Password@123
    depends_on:
      database:
        condition: service_healthy

  database:
    platform: "linux/amd64"
    image: mysql:8.0-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vetcare
      MYSQL_ROOT_PASSWORD: Password@123
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u VetCare_DB --password=Password@123
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  adminer:
    platform: "linux/amd64"
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  db:













#version: '3.8'
#services:
#  web:
#    platform: "linux/amd64"
#    build: .
#    ports:
#      - "8080:8080"
##  mysql-db:
##    image: mysql:8.0
##    environment:
##      MYSQL_ROOT_PASSWORD: password
##      MYSQL_DATABASE: vetcare
##      MYSQL_USER: VetCare_DB
##      MYSQL_PASSWORD: Password@123
##    ports:
##      - "3306:3306"
