CREATE TABLE IF NOT EXISTS TreatmentPlans (
    TreatmentPlanID INT AUTO_INCREMENT PRIMARY KEY,
    PetID INT,
    Diagnosis VARCHAR(255) NOT NULL,
    TreatmentType VARCHAR(100),
    TreatmentDescription VARCHAR(255) NOT NULL,
    PetCondition VARCHAR(255),
    IsEmergency BOOLEAN DEFAULT FALSE,
    StartDate DATE NOT NULL,
    EndDate DATE,
    PrescribedMedications VARCHAR(255),
    TreatmentDuration VARCHAR(100),
    NextSteps VARCHAR(255),
    VetName VARCHAR(100),
    FollowUpDate DATE,
    CostEstimate DECIMAL(10, 2),
    TreatmentOutcome VARCHAR(255),
    TreatmentNotes TEXT,
    ClinicLocation VARCHAR(255),
    IsInsured BOOLEAN DEFAULT FALSE,
    InsuranceDetails VARCHAR(255),
    PaymentStatus VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PetID) REFERENCES pet_info(PetID) ON DELETE CASCADE
);
