CREATE TABLE VETERINARIAN (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    clinicId BIGINT NOT NULL,
    FOREIGN KEY (clinicId) REFERENCES CLINIC(id) ON DELETE CASCADE ON UPDATE CASCADE
);
