INSERT INTO VETERINARIAN (name, clinicId, email) VALUES
('Dr. Alice Smith', 1, 'alice.smith@healthypaws.com'),
('Dr. Bob Johnson', 1, 'bob.johnson@healthypaws.com'),
('Dr. Carol White', 1, 'carol.white@healthypaws.com'),
('Dr. David Brown', 2, 'david.brown@happytails.com'),
('Dr. Emily Davis', 2, 'emily.davis@happytails.com'),
('Dr. Frank Miller', 2, 'frank.miller@happytails.com'),
('Dr. Grace Wilson', 3, 'grace.wilson@pawprints.com'),
('Dr. Henry Moore', 3, 'henry.moore@pawprints.com'),
('Dr. Irene Taylor', 3, 'irene.taylor@pawprints.com'),
('Dr. Jack Anderson', 4, 'jack.anderson@petcareplus.com'),
('Dr. Karen Thomas', 4, 'karen.thomas@petcareplus.com'),
('Dr. Larry Martinez', 4, 'larry.martinez@petcareplus.com'),
('Dr. Megan Clark', 5, 'megan.clark@animalhealth.com'),
('Dr. Nick Lewis', 5, 'nick.lewis@animalhealth.com'),
('Dr. Olivia Walker', 5, 'olivia.walker@animalhealth.com');