//function downloadPDF() {
//    const { jsPDF } = window.jspdf;
//    const doc = new jsPDF();
//
//    const petName = document.querySelector('h2').textContent.trim();
//    const vaccineRecords = document.querySelectorAll('.vaccination-record');
//
//    const lineHeight = 10;
//    let yPosition = 20;
//
//    doc.setFontSize(16);
//    doc.setFont('helvetica', 'bold');
//    doc.text("Pet Vaccination Records", 105, yPosition, { align: 'center' });
//    yPosition += lineHeight + 10;
//
//    doc.setFontSize(14);
//    doc.text(`Pet Name: ${petName}`, 10, yPosition);
//    yPosition += lineHeight + 5;
//
//    doc.setFontSize(12);
//    doc.setFont('helvetica', 'bold');
//    doc.text('Vaccination Details', 10, yPosition);
//    yPosition += lineHeight;
//
//    doc.setFont('helvetica', 'normal');
//
//    vaccineRecords.forEach(record => {
//        const vaccineName = record.querySelector('.card-title').textContent.trim();
//        const administeredDate = record.querySelector('.card-text span').textContent.trim();
//        const nextDueDate = record.querySelector('.card-text:nth-child(3) span').textContent.trim();
//        const boosterRequired = record.querySelector('.card-text:nth-child(4) span').textContent.trim();
//        const dosage = record.querySelector('.card-text:nth-child(5) span').textContent.trim();
//        const veterinarian = record.querySelector('.card-text:nth-child(6) span').textContent.trim();
//        const clinic = record.querySelector('.card-text:nth-child(7) span').textContent.trim();
//        const status = record.querySelector('.card-text:nth-child(8) span').textContent.trim();
//        const additionalNotes = record.querySelector('.card-text:nth-child(9) span').textContent.trim();
//
//        if (yPosition > 270) {
//            doc.addPage();
//            yPosition = 20;
//        }
//
//        doc.text(`Vaccine Name: ${vaccineName}`, 10, yPosition);
//        yPosition += lineHeight;
//        doc.text(`Administered Date: ${administeredDate}`, 10, yPosition);
//        yPosition += lineHeight;
//        doc.text(`Next Due Date: ${nextDueDate}`, 10, yPosition);
//        yPosition += lineHeight;
//        doc.text(`Booster Required: ${boosterRequired}`, 10, yPosition);
//        yPosition += lineHeight;
//        doc.text(`Dosage: ${dosage}`, 10, yPosition);
//        yPosition += lineHeight;
//        doc.text(`Veterinarian: ${veterinarian}`, 10, yPosition);
//        yPosition += lineHeight;
//        doc.text(`Clinic: ${clinic}`, 10, yPosition);
//        yPosition += lineHeight;
//        doc.text(`Status: ${status}`, 10, yPosition);
//        yPosition += lineHeight;
//        doc.text(`Additional Notes: ${additionalNotes}`, 10, yPosition);
//        yPosition += lineHeight + 5;
//    });
//
//    doc.setFontSize(10);
//    doc.setTextColor(100);
//    doc.text("Generated by VetCare System", 10, 280);
//
//    doc.save(`${petName}-vaccination-records.pdf`);
//}
//
//
//    function shareRecords() {
//    if (navigator.share) {
//        try {
//            const petName = document.querySelector('h2').textContent.trim();
//            const vaccineName = document.querySelector('.vaccination-record .card-title').textContent.trim();
//            const nextDueDate = document.querySelector('.vaccination-record .card-text:nth-child(3) span').textContent.trim();
//
//            const shareTitle = `Vaccination Records for ${petName}`;
//            const shareText = `Latest Vaccine: ${vaccineName}\nNext Due Date: ${nextDueDate}`;
//            const shareURL = window.location.href;
//
//            navigator.share({
//                title: shareTitle,
//                text: shareText,
//                url: shareURL
//            }).then(() => {
//                console.log('Records shared successfully');
//                alert('Vaccination Records shared successfully!');
//            }).catch((error) => {
//                console.error('Error sharing records:', error);
//                alert('Failed to share the records.');
//            });
//        } catch (error) {
//            console.error('Error gathering information for sharing:', error);
//            alert('Could not gather information for sharing.');
//        }
//    } else {
//        alert('Web Share API is not supported in this browser.');
//    }
//}

function selectPet() {
   const petSelectElement = document.getElementById('petSelect');
   const petId = petSelectElement.value;
   if (petId && petId !== '') {
       window.location.href = `/vaccination?petId=${petId}`;
   } else {
       alert('Please select a valid pet from the list.');
   }
}

function scrollLeft() {
    const container = document.querySelector('.vaccination-records-row');
    const maxScrollLeft = 0;
    const currentScrollLeft = container.scrollLeft;

    if (currentScrollLeft > maxScrollLeft) {
        container.scrollBy({ left: -300, behavior: 'smooth' });
    }
}

function scrollRight() {
    const container = document.querySelector('.vaccination-records-row');
    const maxScrollLeft = container.scrollWidth - container.clientWidth;
    const currentScrollLeft = container.scrollLeft;

    if (currentScrollLeft < maxScrollLeft) {
        container.scrollBy({ left: 300, behavior: 'smooth' });
    }
}
