CREATE TABLE IF NOT EXISTS PrescriptionRefillRequests (
    RefillRequestID INT AUTO_INCREMENT PRIMARY KEY,
    PetID INT NOT NULL,
    Medications TEXT NOT NULL,
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL,
    Postcode VARCHAR(20) NOT NULL,
    Notes TEXT,
    RequestDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PetID) REFERENCES pet_info(PetID) ON DELETE CASCADE
);
