CREATE TABLE IF NOT EXISTS pet_info (
    PetID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Age INT,
    Gender VARCHAR(10),
    Weight DECIMAL(5, 2),
    Breed VARCHAR(100),
    BirthDate DATE,
    OwnerId BIGINT NOT NULL
);