function downloadPDF() {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    const petName = document.querySelector('h3').textContent.trim();
    const diagnosis = document.querySelector('tr:nth-child(1) td:nth-child(2)').textContent.trim();
    const treatmentType = document.querySelector('tr:nth-child(2) td:nth-child(2)').textContent.trim();
    const petCondition = document.querySelector('tr:nth-child(3) td:nth-child(2)').textContent.trim();
    const isEmergency = document.querySelector('tr:nth-child(4) td:nth-child(2)').textContent.trim();
    const startDate = document.querySelector('tr:nth-child(5) td:nth-child(2)').textContent.trim();
    const endDate = document.querySelector('tr:nth-child(6) td:nth-child(2)').textContent.trim();
    const prescribedMedications = document.querySelector('tr:nth-child(7) td:nth-child(2)').textContent.trim();
    const treatmentDuration = document.querySelector('tr:nth-child(8) td:nth-child(2)').textContent.trim();
    const nextSteps = document.querySelector('tr:nth-child(9) td:nth-child(2)').textContent.trim();
    const vetName = document.querySelector('tr:nth-child(10) td:nth-child(2)').textContent.trim();
    const followUpDate = document.querySelector('tr:nth-child(11) td:nth-child(2)').textContent.trim();
    const costEstimate = document.querySelector('tr:nth-child(12) td:nth-child(2)').textContent.trim();
    const treatmentOutcome = document.querySelector('tr:nth-child(13) td:nth-child(2)').textContent.trim();
    const clinicLocation = document.querySelector('tr:nth-child(14) td:nth-child(2)').textContent.trim();
    const isInsured = document.querySelector('tr:nth-child(15) td:nth-child(2)').textContent.trim();
    const insuranceDetails = document.querySelector('tr:nth-child(16) td:nth-child(2)').textContent.trim();
    const paymentStatus = document.querySelector('tr:nth-child(17) td:nth-child(2)').textContent.trim();

    const lineHeight = 10;
    let yPosition = 20;

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text("Pet Treatment Plan", 105, yPosition, { align: 'center' });
    yPosition += lineHeight + 10;


    doc.setFontSize(14);
    doc.text(`Pet Name: ${petName}`, 10, yPosition);
    yPosition += lineHeight + 5;


    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Treatment Details', 10, yPosition);
    yPosition += lineHeight;


    doc.setFont('helvetica', 'normal');

    const details = [
        { label: 'Diagnosis', value: diagnosis },
        { label: 'Treatment Type', value: treatmentType },
        { label: 'Pet Condition', value: petCondition },
        { label: 'Is Emergency', value: isEmergency },
        { label: 'Start Date', value: startDate },
        { label: 'End Date', value: endDate },
        { label: 'Prescribed Medications', value: prescribedMedications },
        { label: 'Treatment Duration', value: treatmentDuration },
        { label: 'Next Steps', value: nextSteps },
        { label: 'Vet Name', value: vetName },
        { label: 'Follow-Up Date', value: followUpDate },
        { label: 'Cost Estimate', value: costEstimate },
        { label: 'Treatment Outcome', value: treatmentOutcome },
        { label: 'Clinic Location', value: clinicLocation },
        { label: 'Is Insured', value: isInsured },
        { label: 'Insurance Details', value: insuranceDetails },
        { label: 'Payment Status', value: paymentStatus }
    ];

    details.forEach(detail => {
        if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
        }
        doc.text(`${detail.label}: `, 10, yPosition);
        doc.setFont('helvetica', 'bold');
        doc.text(detail.value, 70, yPosition);
        doc.setFont('helvetica', 'normal');
        yPosition += lineHeight;
    });


    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by VetCare System", 10, 280);


    doc.save(`${petName}-treatment-plan.pdf`);
}

function shareRecords() {

    if (navigator.share) {
        try {
            const petName = document.querySelector('h3').textContent.trim();
            const diagnosis = document.querySelector('tr:nth-child(1) td:nth-child(2)').textContent.trim();
            const treatmentType = document.querySelector('tr:nth-child(2) td:nth-child(2)').textContent.trim();
            const nextSteps = document.querySelector('tr:nth-child(9) td:nth-child(2)').textContent.trim();
            const followUpDate = document.querySelector('tr:nth-child(11) td:nth-child(2)').textContent.trim();


            const shareTitle = `Treatment Plan for ${petName}`;
            const shareText = `Diagnosis: ${diagnosis}\nTreatment Type: ${treatmentType}\nNext Steps: ${nextSteps}\nFollow-Up Date: ${followUpDate}`;
            const shareURL = window.location.href;


            navigator.share({
                title: shareTitle,
                text: shareText,
                url: shareURL
            }).then(() => {
                console.log('Records shared successfully');
                alert('Treatment Plan shared successfully!');
            }).catch((error) => {
                console.error('Error sharing records:', error);
                alert('Failed to share the records.');
            });
        } catch (error) {
            console.error('Error gathering information for sharing:', error);
            alert('Could not gather information for sharing.');
        }
    } else {

        alert('Web Share API is not supported in this browser.');
    }
}

function selectPet() {
   const petSelectElement = document.getElementById('petSelect');
   const petId = petSelectElement.value;
   if (petId && petId !== '') {
       window.location.href = `/treatmentPlan?petId=${petId}`;
   } else {
       alert('Please select a valid pet from the list.');
   }
}

